// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewIdentity() {
  return window['go']['main']['App']['CreateNewIdentity']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetMyID() {
  return window['go']['main']['App']['GetMyID']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function ImportKey(arg1) {
  return window['go']['main']['App']['ImportKey'](arg1);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3);
}
