// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNewIdentity():Promise<string>;

export function GetChatHistory(arg1:string):Promise<Array<main.Message>>;

export function GetMessages():Promise<Array<main.Message>>;

export function GetMyID():Promise<string>;

export function GetProfile():Promise<Record<string, any>>;

export function ImportKey(arg1:string):Promise<string>;

export function SearchUsers(arg1:string):Promise<Array<Record<string, any>>>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string):Promise<void>;
